name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build --output type=tar,dest=build64/build64.tar . --file Dockerfile --tag wine64:$(date +%s)
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: |
            build64/build64.tar
  
